const AUTH_STACK: string = "AUTH_STACK";
const APP_BOTTOM_TAB_STACK: string = "APP_BOTTOM_TAB_STACK";
const HOME_STACK: string = "HOME_STACK";

export { AUTH_STACK, APP_BOTTOM_TAB_STACK, HOME_STACK };
